//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tesis
{
    using System.Collections.Generic;
    
    public partial class casestudies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public casestudies()
        {
            this.initialcharges = new HashSet<initialcharges>();
            this.sections = new HashSet<sections>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public System.DateTime Created { get; set; }
        public byte PreparationTime { get; set; }
        public byte AcceleratedPreparationTime { get; set; }
        public byte FillTime { get; set; }
        public byte ExistingFillTime { get; set; }
        public byte DeliveryTime { get; set; }
        public byte CourierDeliveryTime { get; set; }
        public short PurchaseOrderRecharge { get; set; }
        public double CourierCharges { get; set; }
        public int PreparationCost { get; set; }
        public double AnnualMaintenanceCost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<initialcharges> initialcharges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sections> sections { get; set; }
    }
}
