//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tesis
{

    public partial class documents
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Path { get; set; }
    }
}
