//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tesis
{

    public partial class evaluationusers
    {
        public System.Guid Id { get; set; }
        public bool Active { get; set; }
        public System.Guid EvaluationId { get; set; }
        public string UserId { get; set; }
        public int Calification { get; set; }
        public int Total { get; set; }
    
        public virtual evaluations evaluations { get; set; }
        public virtual users users { get; set; }
    }
}
