//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tesis
{
    using System;
    using System.Collections.Generic;
    
    public partial class initialcharges
    {
        public System.Guid Id { get; set; }
        public short Demand { get; set; }
        public short Stddev { get; set; }
        public int Price { get; set; }
        public short SecurityStock { get; set; }
        public int InitialStock { get; set; }
        public System.Guid ProductId { get; set; }
        public System.Guid CaseStudyId { get; set; }
    
        public virtual casestudies casestudies { get; set; }
        public virtual products products { get; set; }
    }
}
