//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tesis
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<casestudies> casestudies { get; set; }
        public virtual DbSet<documents> documents { get; set; }
        public virtual DbSet<evaluations> evaluations { get; set; }
        public virtual DbSet<evaluationusers> evaluationusers { get; set; }
        public virtual DbSet<groups> groups { get; set; }
        public virtual DbSet<initialcharges> initialcharges { get; set; }
        public virtual DbSet<products> products { get; set; }
        public virtual DbSet<questionoptions> questionoptions { get; set; }
        public virtual DbSet<questions> questions { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<sections> sections { get; set; }
        public virtual DbSet<semesters> semesters { get; set; }
        public virtual DbSet<userclaims> userclaims { get; set; }
        public virtual DbSet<userlogin> userlogin { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
