//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tesis
{
    using System;
    using System.Collections.Generic;
    
    public partial class questionoptions
    {
        public System.Guid Id { get; set; }
        public bool IsCorrectOption { get; set; }
        public string Option { get; set; }
        public System.Guid QuestionId { get; set; }
    
        public virtual questions questions { get; set; }
    }
}
